<?php

return [
    'admin' => [
        [
            'label' => 'Dashboard',
            'route' => 'admin.dashboard',
            'permission' => 'dashboard.view',
            'icon' => 'M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6',
        ],
        [
            'group' => 'Website',
            'icon' => 'M21 12a9 9 0 01-9 9m9-9a9 9 0 00-9-9m9 9H3m9 9a9 9 0 01-9-9m9 9c1.657 0 3-4.03 3-9s-1.343-9-3-9m0 18c-1.657 0-3-4.03-3-9s1.343-9 3-9m-9 9a9 9 0 019-9',
            'items' => [
                ['label' => 'Institute Profile', 'route' => 'admin.company-profile.edit', 'permission' => 'settings.view'],
                ['label' => 'Testimonials', 'route' => 'admin.company-page.testimonials', 'permission' => 'settings.view'],
                ['label' => 'Reviews', 'route' => 'admin.company-page.reviews', 'permission' => 'settings.view'],
                ['label' => 'Enquiries', 'route' => 'admin.company-page.enquiries', 'permission' => 'settings.view'],
                ['label' => 'Gallery', 'route' => 'admin.company-page.gallery', 'permission' => 'settings.view'],
                ['label' => 'Videos', 'route' => 'admin.company-page.videos', 'permission' => 'settings.view'],
                ['label' => 'Blogs', 'route' => 'admin.company-page.blogs', 'permission' => 'settings.view'],
                ['label' => 'Team', 'route' => 'admin.company-page.team', 'permission' => 'settings.view'],
                ['label' => 'Homepage Sections', 'route' => 'admin.website-sections.index', 'permission' => 'settings.view'],
                ['label' => 'Preview Website', 'route' => 'admin.website-sections.preview', 'permission' => 'settings.view', 'hidden' => true],
                ['label' => 'Theme Settings', 'route' => 'admin.settings.index', 'permission' => 'settings.view', 'hidden' => true],
                ['label' => 'Social Links', 'route' => 'admin.settings.social', 'permission' => 'settings.view'],
            ],
        ],
        [
            'group' => 'Course Management',
            'icon' => 'M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253',
            'items' => [
                ['label' => 'Curriculum Builder', 'route' => 'admin.courses.index', 'permission' => 'products.view', 'active_routes' => [
                    'admin.courses.builder',
                    'admin.courses.edit',
                    'admin.courses.create',
                    'admin.courses.settings.*',
                    'admin.courses.sections.*',
                    'admin.lessons.*',
                ]],
                ['label' => 'Quizzes', 'route' => 'admin.quizzes.index', 'permission' => 'products.view'],
                ['label' => 'Assignments', 'route' => 'admin.assignments.index', 'permission' => 'products.view'],
                ['label' => 'Live Classes', 'route' => 'admin.live-classes.index', 'permission' => 'products.view'],
            ],
        ],
        [
            'group' => 'Products',
            'icon' => 'M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4',
            'items' => [
                ['label' => 'Courses', 'route' => 'admin.courses.index', 'permission' => 'products.view', 'active_routes' => ['admin.courses.index']],
                ['label' => 'Mock test', 'route' => 'admin.mock-tests.index', 'permission' => 'products.view'],
                ['label' => 'Test Series', 'route' => 'admin.test-series.index', 'permission' => 'products.view'],
                ['label' => 'Bundles', 'route' => 'admin.bundles.index', 'permission' => 'products.view'],
                ['label' => 'Batch', 'route' => 'admin.batches.index', 'permission' => 'products.view'],
                ['label' => 'Poll', 'route' => 'admin.polls.index', 'permission' => 'products.view'],
                ['label' => 'Tracks', 'route' => 'admin.tracks.index', 'permission' => 'products.view'],
                ['label' => 'Code', 'route' => 'admin.code.index', 'permission' => 'products.view', 'hidden' => true],
                ['label' => 'More Products', 'route' => 'admin.more-products.index', 'permission' => 'products.view'],
                ['label' => 'Question Pool', 'route' => 'admin.question-pools.index', 'permission' => 'products.view'],
                ['label' => 'All Questions', 'route' => 'admin.questions.index', 'permission' => 'products.view'],
                ['label' => 'Classification', 'route' => 'admin.classification.index', 'permission' => 'products.view'],
                ['label' => 'Utilities', 'route' => 'admin.utilities.index', 'permission' => 'products.view'],
            ],
        ],
        [
            'group' => 'Users',
            'icon' => 'M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z',
            'items' => [
                ['label' => 'Learners', 'route' => 'admin.learners.index', 'permission' => 'learners.view'],
                ['label' => 'Groups', 'route' => 'admin.groups.index', 'permission' => 'learners.view'],
                ['label' => 'Instructors', 'route' => 'admin.instructors.index', 'permission' => 'instructors.view'],
                ['label' => 'Sub-Admins', 'route' => 'admin.sub-admins.index', 'permission' => 'sub_admins.view'],
                ['label' => 'Alumni', 'route' => 'admin.alumni.index', 'permission' => 'alumni.view'],
                ['label' => 'Parent Links', 'route' => 'admin.parent-links.index', 'permission' => 'parent.view'],
                ['label' => 'Contacts', 'route' => 'admin.contacts.index', 'permission' => 'learners.view', 'badge' => 'New'],
                ['label' => 'Legal Documents', 'route' => 'admin.legal-documents.index', 'permission' => 'learners.view', 'badge' => 'New'],
            ],
        ],
        [
            'group' => 'Sales',
            'icon' => 'M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z',
            'items' => [
                ['label' => 'Orders', 'route' => 'admin.orders.index', 'permission' => 'sales.view'],
                ['label' => 'Payments', 'route' => 'admin.payments.index', 'permission' => 'sales.view'],
                ['label' => 'Payment / Razorpay', 'route' => 'admin.settings.index', 'params' => ['tab' => 'payment'], 'permission' => 'settings.view'],
                ['label' => 'Checkout Consent', 'route' => 'admin.checkout-consents.index', 'permission' => 'sales.view'],
                ['label' => 'Coupons', 'route' => 'admin.marketing.coupons', 'permission' => 'sales.view'],
            ],
        ],
        [
            'group' => 'Teaching',
            'icon' => 'M12 14l9-5-9-5-9 5 9 5z|M12 14l6.16-3.422a12.083 12.083 0 01.665 6.479A11.952 11.952 0 0012 20.055a11.952 11.952 0 00-6.824-2.998 12.078 12.078 0 01.665-6.479L12 14z',
            'items' => [
                ['label' => 'Batches', 'route' => 'admin.batches.index', 'permission' => 'batches.view'],
                ['label' => 'Certificates', 'route' => 'admin.certificates.index', 'permission' => 'products.view'],
                ['label' => 'Certificate Renewal', 'route' => 'admin.certificates.renewals.index', 'permission' => 'certificates_renewal.view'],
                ['label' => 'Exam Proctoring', 'route' => 'admin.proctoring.index', 'permission' => 'proctoring.view'],
            ],
        ],
        [
            'group' => 'Community',
            'icon' => 'M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z',
            'items' => [
                ['label' => 'Communities', 'route' => 'admin.communities.index', 'permission' => 'community.view'],
                ['label' => 'Discussions', 'route' => 'admin.discussions.index', 'permission' => 'community.view'],
            ],
        ],
        [
            'group' => 'Admin Management',
            'icon' => 'M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z',
            'items' => [
                ['label' => 'Roles', 'route' => 'admin.roles.index', 'permission' => 'sub_admins.manage'],
                ['label' => 'Permissions', 'route' => 'admin.permissions.index', 'permission' => 'sub_admins.manage'],
            ],
        ],
        [
            'group' => 'Insights',
            'icon' => 'M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z',
            'items' => [
                ['label' => 'Dashboard', 'route' => 'admin.insights.dashboard', 'permission' => 'insights.view'],
                ['label' => 'School Vitals', 'route' => 'admin.insights.school-vitals', 'permission' => 'insights.view'],
                ['label' => 'Sales Insight', 'route' => 'admin.insights.sales.index', 'permission' => 'insights.view'],
                ['label' => 'Live Dashboard', 'route' => 'admin.insights.live.index', 'permission' => 'insights.view'],
                ['label' => 'Marketing Insight', 'route' => 'admin.insights.marketing.index', 'permission' => 'insights.view'],
                ['label' => 'Messenger Insight', 'route' => 'admin.insights.messenger.index', 'permission' => 'insights.view'],
            ],
        ],
        [
            'group' => 'Reports',
            'icon' => 'M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z',
            'items' => [
                ['label' => 'All Reports', 'route' => 'admin.reports.index', 'permission' => 'reports.view'],
                ['label' => 'Learner Enrollments', 'route' => 'admin.reports.enrollments', 'permission' => 'reports.view'],
                ['label' => 'Transactions', 'route' => 'admin.reports.transactions', 'permission' => 'reports.view'],
                ['label' => 'Payment Gateways', 'route' => 'admin.reports.payment-gateways', 'permission' => 'reports.view'],
                ['label' => 'School Payouts', 'route' => 'admin.reports.school-payouts', 'permission' => 'reports.view'],
                ['label' => 'Product Progress', 'route' => 'admin.reports.progress.index', 'permission' => 'reports.view'],
                ['label' => 'Bundle Progress', 'route' => 'admin.reports.bundle-progress', 'permission' => 'reports.view'],
                ['label' => 'Custom Product Progress', 'route' => 'admin.reports.custom-product-progress', 'permission' => 'reports.view'],
                ['label' => 'Test Series Scores', 'route' => 'admin.reports.test-series-scores', 'permission' => 'reports.view'],
                ['label' => 'Batches Report', 'route' => 'admin.reports.batches', 'permission' => 'reports.view'],
                ['label' => 'Sales Reports', 'route' => 'admin.reports.sales.index', 'permission' => 'reports.view'],
                ['label' => 'Learners Report', 'route' => 'admin.reports.learners', 'permission' => 'reports.view'],
                ['label' => 'Course Report', 'route' => 'admin.reports.courses', 'permission' => 'reports.view'],
                ['label' => 'Bundle Report', 'route' => 'admin.reports.bundles', 'permission' => 'reports.view'],
                ['label' => 'Zoom Insights', 'route' => 'admin.reports.zoom-insights', 'permission' => 'reports.view'],
                ['label' => 'Live Class Attendance', 'route' => 'admin.reports.live-class-attendance', 'permission' => 'reports.view'],
                ['label' => 'Resource Usage', 'route' => 'admin.reports.resource-usage', 'permission' => 'reports.view'],
                ['label' => 'Super Live Lessons', 'route' => 'admin.reports.super-live-lessons', 'permission' => 'reports.view'],
                ['label' => 'Certificates Report', 'route' => 'admin.reports.certificates', 'permission' => 'reports.view'],
            ],
        ],
        [
            'group' => 'Settings',
            'icon' => 'M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4',
            'items' => [
                ['label' => 'Institute Profile', 'route' => 'admin.company-profile.edit', 'permission' => 'settings.view'],
                ['label' => 'Website Settings', 'route' => 'admin.settings.index', 'permission' => 'settings.view'],
                ['label' => 'Payment / Razorpay', 'route' => 'admin.settings.index', 'params' => ['tab' => 'payment'], 'permission' => 'settings.view'],
                ['label' => 'Social Links', 'route' => 'admin.settings.social', 'permission' => 'settings.view'],
                ['label' => 'Sidebar Settings', 'route' => 'admin.settings.sidebar', 'permission' => 'settings.view'],
                ['label' => 'Compliance Center', 'route' => 'admin.compliance.index', 'permission' => 'compliance.view'],
                ['label' => 'Notification Center', 'route' => 'admin.notifications.index', 'permission' => 'notifications.view'],
            ],
        ],
    ],
];
