<?php

return [
    'groups' => [
        'general' => [
            'label' => 'General',
            'description' => 'Setup general course settings',
            'panels' => ['branding', 'seo', 'tags', 'faqs', 'instructors'],
        ],
        'pricing' => [
            'label' => 'Pricing & Permissions',
            'description' => 'Manage pricing and permission settings for your course',
            'panels' => ['pricing-plans', 'android-pricing', 'ios-pricing', 'permissions'],
        ],
        'features' => [
            'label' => 'Features',
            'description' => 'Configure learner-facing course features',
            'panels' => [
                'ratings-reviews',
                'discussions-bookmarks',
                'leaderboard',
                'certificates',
                'content-dripping',
                'learner-configurations',
                'learning-path',
            ],
        ],
        'publish' => [
            'label' => 'Publish/Delete Course',
            'description' => 'Publish, trash, associations, and learner removal',
            'panels' => ['publish', 'trash', 'associated-contents', 'remove-learners'],
        ],
    ],

    'panels' => [
        'branding' => [
            'title' => 'Branding',
            'description' => 'Add details about your course and manage brand settings',
            'icon' => 'branding',
            'group' => 'general',
            'status_key' => 'branding',
        ],
        'seo' => [
            'title' => 'SEO',
            'description' => 'Add SEO details to help bring your course on top of the search results',
            'icon' => 'seo',
            'group' => 'general',
            'status_key' => 'seo',
        ],
        'tags' => [
            'title' => 'Tags',
            'description' => 'Add course tags to make the course easy to filter for learners',
            'icon' => 'tags',
            'group' => 'general',
            'status_key' => 'tags',
        ],
        'faqs' => [
            'title' => 'FAQs',
            'description' => 'Add and manage frequently asked questions for your course',
            'icon' => 'faqs',
            'group' => 'general',
            'status_key' => 'faqs',
        ],
        'instructors' => [
            'title' => 'Instructors',
            'description' => 'Add instructors associated with the course',
            'icon' => 'instructors',
            'group' => 'general',
            'status_key' => 'instructors',
        ],
        'pricing-plans' => [
            'title' => 'Pricing Plans',
            'description' => 'Manage pricing and expiry details for your product',
            'icon' => 'pricing',
            'group' => 'pricing',
            'status_key' => 'pricing_plans',
        ],
        'android-pricing' => [
            'title' => 'Android Pricing',
            'description' => 'Configure Android in-app purchase pricing',
            'icon' => 'android',
            'group' => 'pricing',
            'status_key' => 'android',
        ],
        'ios-pricing' => [
            'title' => 'iOS Pricing',
            'description' => 'Configure iOS App Store pricing',
            'icon' => 'ios',
            'group' => 'pricing',
            'status_key' => 'ios',
        ],
        'permissions' => [
            'title' => 'Permissions',
            'description' => 'Control how and where this course can be sold and accessed',
            'icon' => 'permissions',
            'group' => 'pricing',
            'status_key' => 'permissions',
        ],
        'ratings-reviews' => [
            'title' => 'Ratings & Reviews',
            'description' => 'Configure ratings and written reviews for this course',
            'icon' => 'reviews',
            'group' => 'features',
            'status_key' => 'reviews',
        ],
        'discussions-bookmarks' => [
            'title' => 'Discussions & Bookmarks',
            'description' => 'Enable discussions and lesson bookmarks for learners',
            'icon' => 'discussions',
            'group' => 'features',
            'status_key' => 'discussions',
        ],
        'leaderboard' => [
            'title' => 'Leaderboard',
            'description' => 'Rank learners by progress, scores, and activity',
            'icon' => 'leaderboard',
            'group' => 'features',
            'status_key' => 'leaderboard',
        ],
        'certificates' => [
            'title' => 'Certificates',
            'description' => 'Enable course certification based on completion criteria',
            'icon' => 'certificates',
            'group' => 'features',
            'status_key' => 'certificates',
        ],
        'content-dripping' => [
            'title' => 'Content Dripping',
            'description' => 'Control when lessons and modules become available',
            'icon' => 'drip',
            'group' => 'features',
            'status_key' => 'drip',
        ],
        'learner-configurations' => [
            'title' => 'Learner Configurations',
            'description' => 'Configure learner access, completion, and progress rules',
            'icon' => 'learner',
            'group' => 'features',
            'status_key' => 'learner',
        ],
        'learning-path' => [
            'title' => 'Learning Path',
            'description' => 'Enforce sequential learning and lesson unlock rules',
            'icon' => 'path',
            'group' => 'features',
            'status_key' => 'learning_path',
        ],
        'publish' => [
            'title' => 'Publish Course',
            'description' => 'Make your course live or keep it unpublished',
            'icon' => 'publish',
            'group' => 'publish',
            'status_key' => 'publish',
        ],
        'trash' => [
            'title' => 'Move To Trash',
            'description' => 'Soft-delete this course with restore support',
            'icon' => 'trash',
            'group' => 'publish',
            'status_key' => 'trash',
        ],
        'associated-contents' => [
            'title' => 'Associated Contents',
            'description' => 'View bundles, segments, categories, and related content',
            'icon' => 'associated',
            'group' => 'publish',
            'status_key' => 'associated',
        ],
        'remove-learners' => [
            'title' => 'Remove Learners',
            'description' => 'Remove learner access from this course and audit the change',
            'icon' => 'remove_learners',
            'group' => 'publish',
            'status_key' => 'remove_learners',
        ],
    ],
];
