<?php

return [
    'brand' => 'StudyNest',
    'tagline' => 'The Most Secure LMS to Sell Courses Online',
    'email' => 'hello@studynest.com',
    'phone' => '080 4736 1000',
    'address' => [
        'StudyNest Insight Private Limited',
        '#110, Krishna Garden Main Road',
        'Rajarajeshwari Nagar, Bangalore 560098',
    ],
    'cta' => [
        'trial' => '/signup',
        'demo' => '/product-demo',
        'login' => '/student/login',
        'student_register' => '/student/register',
        'company_login' => '/login',
    ],

    'products' => [
        'sell-online-courses' => [
            'title' => 'Online Courses',
            'menu' => 'Online Courses',
            'menu_desc' => 'Create, publish and market your courses online',
            'group' => 'sell',
            'icon' => 'fa-book',
            'caption' => 'Products',
            'summary' => 'Convert your knowledge into valuable course assets and sell online from your own brand.',
            'body' => 'Create structured courses with videos, documents, quizzes, and drip content. Manage enrollments, track progress, and deliver a polished learning experience from your branded website and apps.',
            'features' => [
                'Drag-and-drop course builder',
                'Drip lessons and certificates',
                'Student progress tracking',
                'Secure video streaming',
                'Coupons and pricing plans',
            ],
        ],
        'sell-mock-tests' => [
            'title' => 'Mock Test and Test Series',
            'menu' => 'Mock Test and Test Series',
            'menu_desc' => 'Sell exam specific mock tests and test series',
            'group' => 'sell',
            'icon' => 'fa-clipboard',
            'caption' => 'Products',
            'summary' => 'Build confidence with mock tests that mirror real exams.',
            'body' => 'Create exam-like mock tests with timers, sections, ranking, and detailed analysis. Perfect for competitive exam institutes and coaching academies.',
            'features' => [
                'Sectional and full-length tests',
                'Negative marking support',
                'Leaderboards and analytics',
                'Question banks and pools',
                'Detailed solution reports',
            ],
        ],
        'sell-digital-products' => [
            'title' => 'Digital Products',
            'menu' => 'Digital Products',
            'menu_desc' => 'Create and sell eBooks, Podcasts and Webinars',
            'group' => 'sell',
            'icon' => 'fa-video-camera',
            'caption' => 'Products',
            'summary' => 'Boost your earnings with ebooks, notes, and downloadable products.',
            'body' => 'Sell digital downloads such as PDFs, notes, study material, and other resources alongside your courses — all from one secure platform.',
            'features' => [
                'Secure file delivery',
                'One-time or subscription pricing',
                'Bundles with courses',
                'Instant checkout',
                'Access control',
            ],
        ],
        'manage-batches-cohorts' => [
            'title' => 'Batch or Cohort',
            'menu' => 'Batch or Cohort',
            'menu_desc' => 'Create batches to enhance group learning & engagement.',
            'group' => 'sell',
            'icon' => 'fa-users',
            'caption' => 'Products',
            'summary' => 'Bring the classroom back and engage learners in cohorts.',
            'body' => 'Run batch-based programs with start dates, schedules, live sessions, and group progress — ideal for structured coaching and bootcamps.',
            'features' => [
                'Batch enrollment',
                'Cohort schedules',
                'Group progress views',
                'Instructor assignment',
                'Live + recorded hybrid learning',
            ],
        ],
        'branded-website-builder' => [
            'title' => 'Branded Website',
            'menu' => 'Branded Website',
            'menu_desc' => 'Increase your reach by creating branded website',
            'group' => 'presence',
            'icon' => 'fa-desktop',
            'caption' => 'Products',
            'summary' => 'Build and manage your branded website. No code, no worries.',
            'body' => 'Launch a professional academy website with landing pages, lead forms, and product pages — fully aligned with your brand identity.',
            'features' => [
                'No-code website builder',
                'Custom domain support',
                'Landing pages and CTAs',
                'SEO-friendly pages',
                'Brand colors and logos',
            ],
        ],
        'branded-mobile-app' => [
            'title' => 'Branded Mobile App',
            'menu' => 'Branded Mobile App',
            'menu_desc' => 'Create your own app ensuring convenience for users on the go',
            'group' => 'presence',
            'icon' => 'fa-mobile',
            'caption' => 'Products',
            'summary' => 'Customised apps to reach learners anytime, anywhere.',
            'body' => 'Give learners a polished mobile experience with your logo, brand colors, and secure content delivery on iOS and Android.',
            'features' => [
                'Custom splash and branding',
                'Secure content playback',
                'Push notifications',
                'Offline-friendly learning',
                'App store publishing support',
            ],
        ],
        'create-learning-community' => [
            'title' => 'Communities',
            'menu' => 'Communities',
            'menu_desc' => 'Create and grow student communities with StudyNest',
            'group' => 'presence',
            'icon' => 'fa-graduation-cap',
            'caption' => 'Products',
            'summary' => 'Build a space for learning, growth, and motivation.',
            'body' => 'Create discussion spaces where learners ask questions, share progress, and stay connected with mentors and peers.',
            'features' => [
                'Discussion forums',
                'Member management',
                'Moderation tools',
                'Engagement notifications',
                'Course-linked communities',
            ],
        ],
        'marketing-sales-hub' => [
            'title' => 'Marketing & Sales Tools',
            'menu' => 'Marketing & Sales Tools',
            'menu_desc' => 'Generate high-quality leads with strong sales potential',
            'group' => 'market',
            'icon' => 'fa-bullhorn',
            'caption' => 'Products',
            'summary' => 'Attract students, capture leads, and convert them into learners.',
            'body' => 'Use landing pages, funnels, campaigns, email, push, and WhatsApp messaging to grow enrollments from one marketing hub.',
            'features' => [
                'Landing pages',
                'Lead capture forms',
                'Workflows and funnels',
                'Email, push & WhatsApp',
                'Affiliate tools',
            ],
        ],
        'affiliate-marketing' => [
            'title' => 'Affiliate Marketing',
            'menu' => 'Affiliate Marketing',
            'menu_desc' => 'Boost Sales with Affiliate Marketing for Your Products',
            'group' => 'market',
            'icon' => 'fa-certificate',
            'caption' => 'Products',
            'summary' => 'Grow enrollments through affiliate partners and referral programs.',
            'body' => 'Enable affiliates to promote your courses, track conversions, and reward partners — helping you scale sales with trusted promoters.',
            'features' => [
                'Affiliate link tracking',
                'Commission management',
                'Partner dashboards',
                'Campaign performance reports',
                'Payout workflows',
            ],
        ],
        'payment-options' => [
            'title' => 'Payment Options',
            'menu' => 'Payment Options',
            'menu_desc' => 'Flexible Payment Options for Your Students',
            'group' => 'market',
            'icon' => 'fa-money',
            'caption' => 'Products',
            'summary' => 'Accept payments smoothly with integrated gateways.',
            'body' => 'Offer flexible pricing, coupons, and trusted payment options so students can enroll quickly and securely.',
            'features' => [
                'Multiple payment gateways',
                'Coupons and discounts',
                'One-time and installment plans',
                'Order and invoice tracking',
                'Refund workflows',
            ],
        ],
        'sales-insights' => [
            'title' => 'Sales Insights',
            'menu' => 'Sales Insights',
            'menu_desc' => 'Track and Optimize Your Sales Performance',
            'group' => 'market',
            'icon' => 'fa-bar-chart',
            'caption' => 'Products',
            'summary' => 'Track and optimize your academy sales performance.',
            'body' => 'Monitor revenue, product performance, conversions, and growth trends so you can make smarter decisions and scale faster.',
            'features' => [
                'Revenue dashboards',
                'Product sales reports',
                'Conversion tracking',
                'Coupon and campaign insights',
                'Exportable reports',
            ],
        ],
        'live-class' => [
            'title' => 'Live Class',
            'menu' => 'Live Class',
            'menu_desc' => 'Schedule, teach, and grow with live class tools',
            'group' => null,
            'icon' => 'fa-video-camera',
            'caption' => 'Products',
            'summary' => 'Schedule, teach, and grow with all-in-one live class tools.',
            'body' => 'Host interactive live sessions, manage attendance, and keep learners engaged with recordings and reminders built into your academy workflow.',
            'features' => [
                'Live class scheduling',
                'Attendance tracking',
                'Session recordings',
                'Reminders and notifications',
                'Batch-based live programs',
            ],
        ],
    ],

    'solutions' => [
        'sell-upsc-courses' => [
            'title' => 'UPSC',
            'menu' => 'UPSC',
            'menu_desc' => 'Create Courses for Union Public Service Commission Exam',
            'group' => 'test_prep',
            'icon' => 'fa-graduation-cap',
            'caption' => 'Solutions',
            'summary' => 'Sell UPSC courses, test series, and live mentorship with strong content security.',
            'body' => 'Help aspirants prepare with structured courses, mock tests, current affairs resources, and community support — all under your brand.',
        ],
        'sell-ca-courses' => [
            'title' => 'CA',
            'menu' => 'CA',
            'menu_desc' => 'Create Courses for Chartered Accountancy Exam',
            'group' => 'test_prep',
            'icon' => 'fa-graduation-cap',
            'caption' => 'Solutions',
            'summary' => 'Run CA coaching with courses, mocks, and batch programs.',
            'body' => 'Deliver foundation-to-final CA programs with secure video, practice tests, and cohort-based learning.',
        ],
        'sell-cat-courses' => [
            'title' => 'CAT',
            'menu' => 'CAT',
            'menu_desc' => 'Create Courses for Common Admission Test',
            'group' => 'test_prep',
            'icon' => 'fa-graduation-cap',
            'caption' => 'Solutions',
            'summary' => 'Grow your MBA prep academy with courses and mocks.',
            'body' => 'Offer quant, verbal, and LRDI courses with timed mocks, analytics, and personalized practice paths.',
        ],
        'sell-iit-jee-courses' => [
            'title' => 'IIT JEE',
            'menu' => 'IIT JEE',
            'menu_desc' => 'Create Courses for IIT- Joint Entrance Exam',
            'group' => 'test_prep',
            'icon' => 'fa-graduation-cap',
            'caption' => 'Solutions',
            'summary' => 'Power IIT-JEE coaching with live classes and test series.',
            'body' => 'Combine live teaching, recorded lessons, and rigorous mock tests for engineering entrance preparation.',
        ],
        'sell-gate-courses' => [
            'title' => 'GATE',
            'menu' => 'GATE',
            'menu_desc' => 'Create Courses for Graduate Aptitude Test in Engineering',
            'group' => 'test_prep',
            'icon' => 'fa-graduation-cap',
            'caption' => 'Solutions',
            'summary' => 'Launch GATE programs with structured learning and mocks.',
            'body' => 'Create subject-wise modules, practice sets, and full-length GATE mocks with detailed performance insights.',
        ],
        'sell-gmat-focus-courses' => [
            'title' => 'GMAT Focus',
            'menu' => 'GMAT Focus',
            'menu_desc' => 'Create Courses for Graduate Management Admission Test',
            'group' => 'test_prep',
            'icon' => 'fa-graduation-cap',
            'caption' => 'Solutions',
            'summary' => 'Sell GMAT Focus Edition prep with adaptive practice.',
            'body' => 'Help students prepare for GMAT Focus with targeted lessons, timed mocks, and progress analytics.',
        ],
        'sell-banking-courses' => [
            'title' => 'Banking',
            'menu' => 'Banking',
            'menu_desc' => 'Create Courses for PO, SBI, RBI, NABARD Entrance Exams',
            'group' => 'test_prep',
            'icon' => 'fa-graduation-cap',
            'caption' => 'Solutions',
            'summary' => 'Scale banking exam prep with mocks and live batches.',
            'body' => 'Deliver IBPS, SBI, and other banking exam programs with sectional tests, current affairs, and live doubt sessions.',
        ],
        'sell-coding-courses' => [
            'title' => 'Coding School',
            'menu' => 'Coding School',
            'menu_desc' => 'Create, publish and market coding courses',
            'group' => 'creators',
            'icon' => 'fa-code',
            'caption' => 'Solutions',
            'summary' => 'Give students a space to learn, practice, and grow in programming.',
            'body' => 'Sell coding bootcamps, live cohorts, and project-based courses with community support and progress tracking.',
        ],
        'sell-trading-courses' => [
            'title' => 'Stocks & Trading',
            'menu' => 'Stocks & Trading',
            'menu_desc' => 'Create, publish and market stocks & trading courses',
            'group' => 'creators',
            'icon' => 'fa-line-chart',
            'caption' => 'Solutions',
            'summary' => 'Grow your trading academy with marketing and analytics.',
            'body' => 'Sell stock market and trading courses with live sessions, community spaces, and strong content protection.',
        ],
        'sell-lifestyle-and-fitness-courses' => [
            'title' => 'Lifestyle & Fitness',
            'menu' => 'Lifestyle & Fitness',
            'menu_desc' => 'Create, publish and market lifestyle and fitness courses',
            'group' => 'creators',
            'icon' => 'fa-heartbeat',
            'caption' => 'Solutions',
            'summary' => 'Sell lifestyle, wellness, and fitness programs online.',
            'body' => 'Offer courses, live programs, and digital products for fitness, wellness, and lifestyle creators with secure payments.',
        ],
        'sell-content-creator-courses' => [
            'title' => 'Content Creators',
            'menu' => 'Content Creators',
            'menu_desc' => 'Create, publish and market your content courses',
            'group' => 'creators',
            'icon' => 'fa-play-circle',
            'caption' => 'Solutions',
            'summary' => 'Turn your content into courses and grow your creator academy.',
            'body' => 'Help content creators package videos, community access, and digital products into a branded learning business with secure payments and marketing tools.',
        ],
    ],

    'pages' => [
        'about-us' => [
            'title' => 'About Us',
            'caption' => 'Know Us Better',
            'summary' => 'StudyNest helps institutes protect content, grow students, and lead with confidence.',
            'body' => 'Join 12,000+ institutes already using StudyNest — the secure online course platform built to help educators create, market, and sell courses from their own brand. Our team listens first, acts fast, and keeps improving the platform with your feedback.',
        ],
        'pricing' => [
            'title' => 'Pricing',
            'caption' => 'Plans',
            'summary' => 'Flexible plans for startups and growing institutes.',
            'body' => 'Start with a free trial and scale as you grow. Choose plans that fit launchers, growing academies, and enterprise institutes — with DRM security, branded apps, and marketing tools included based on your needs.',
        ],
        'product-demo' => [
            'title' => 'Product Demo',
            'caption' => 'Book a Tour',
            'summary' => 'See how StudyNest can power your academy growth.',
            'body' => 'Book a guided demo with our team and explore course builder, mock tests, live classes, marketing tools, DRM security, and branded apps tailored to your institute.',
        ],
        'support-migration' => [
            'title' => 'Support & Migration',
            'caption' => 'Support',
            'summary' => 'Navigate your transition with expert support and resources.',
            'body' => 'Moving from another platform? Our support team helps you migrate courses, learners, and content smoothly so you can launch on StudyNest with confidence.',
        ],
        'guides' => [
            'title' => 'Guides',
            'caption' => 'Resources',
            'summary' => 'Library of free templates, eBooks, and useful resources.',
            'body' => 'Explore practical guides and templates to help you create courses, grow enrollments, and run your online academy more effectively with StudyNest.',
        ],
        'drm-security' => [
            'title' => 'DRM Security',
            'caption' => 'Content Protection',
            'summary' => 'Best-in-class DRM security for content protection.',
            'body' => 'Protect your intellectual property with screenshot blocking, screen-recording prevention, parallel login restriction, multi-device limits, piracy monitoring, OTP verification, and watch-time controls.',
        ],
        'corporate-lms' => [
            'title' => 'For Corporate',
            'caption' => 'Corporate LMS',
            'summary' => 'Train teams with a secure, branded learning platform.',
            'body' => 'Use StudyNest for employee training, partner enablement, and corporate academies with secure delivery, progress tracking, and reporting.',
        ],
        'ai' => [
            'title' => 'AI Cofounder',
            'caption' => 'AI Tools',
            'summary' => 'Accelerate content and growth with AI assistance.',
            'body' => 'Use AI-powered tools to speed up course creation, marketing copy, and learner support while keeping your brand and content secure.',
        ],
        'careers' => [
            'title' => 'Careers',
            'caption' => 'Join Us',
            'summary' => 'Build the future of online education with StudyNest.',
            'body' => 'We are a product-driven team helping thousands of educators grow. Explore open roles and help us make secure online teaching better for every institute.',
        ],
        'privacy-policy' => [
            'title' => 'Privacy Policy',
            'caption' => 'Legal',
            'summary' => 'How StudyNest collects and protects your information.',
            'body' => 'We respect your privacy. This page outlines how personal data is collected, used, stored, and protected when you use StudyNest products and services.',
        ],
        'terms-and-conditions' => [
            'title' => 'Terms & Conditions',
            'caption' => 'Legal',
            'summary' => 'Terms that govern use of the StudyNest platform.',
            'body' => 'By using StudyNest, you agree to our terms of service covering accounts, content ownership, payments, acceptable use, and platform responsibilities.',
        ],
    ],

    'customers' => [
        'success-stories' => [
            'title' => 'Success Stories',
            'menu' => 'Success Stories',
            'menu_desc' => 'Get inspired by the success stories of StudyNest customers',
            'icon' => 'fa-book',
            'caption' => 'Customers',
            'summary' => 'Real growth stories from educators using StudyNest.',
            'body' => 'From exam prep to coding and trading academies, institutes use StudyNest to protect content and scale revenue with confidence.',
        ],
        'testimonials' => [
            'title' => 'Testimonials',
            'menu' => 'Testimonials',
            'menu_desc' => 'Listen to what our clients have to say about their experience',
            'icon' => 'fa-star-o',
            'caption' => 'Customers',
            'summary' => 'Real words, real impact from 3000+ happy clients.',
            'body' => 'Educators trust StudyNest for supportive teams, user-friendly tools, and consistent product improvements that help academies grow faster.',
        ],
        'wall-of-love' => [
            'title' => 'Wall Of Love',
            'menu' => 'Wall Of Love',
            'menu_desc' => 'Explore unfiltered stories from educators who made it happen.',
            'icon' => 'fa-heart-o',
            'caption' => 'Customers',
            'summary' => 'Love notes from institutes growing with StudyNest.',
            'body' => 'See what founders and educators share about support quality, platform reliability, and business outcomes after switching to StudyNest.',
        ],
    ],

    'resources_menu' => [
        'product-demo' => [
            'menu' => 'Product Demo',
            'menu_desc' => 'Book a free demo today for any doubts',
            'group' => 'support',
            'icon' => 'fa-desktop',
            'route' => 'website.page',
            'param' => 'product-demo',
        ],
        'help-center' => [
            'menu' => 'Help Center',
            'menu_desc' => 'Connect with us in case you have any doubts or queries',
            'group' => 'support',
            'icon' => 'fa-question-circle',
            'route' => 'website.help-center',
        ],
        'support-migration' => [
            'menu' => 'Support & Migration',
            'menu_desc' => 'Navigate Your Transition with Expert Support and Resources',
            'group' => 'support',
            'icon' => 'fa-cog',
            'route' => 'website.page',
            'param' => 'support-migration',
        ],
        'guides' => [
            'menu' => 'Guides',
            'menu_desc' => 'Library of free templates, eBooks, and useful resources',
            'group' => 'resources',
            'icon' => 'fa-book',
            'route' => 'website.page',
            'param' => 'guides',
        ],
        'whats-new' => [
            'menu' => "What's New",
            'menu_desc' => 'Stay informed about the latest & trendiest updates on StudyNest',
            'group' => 'resources',
            'icon' => 'fa-file-text-o',
            'route' => 'website.whats-new',
        ],
        'blogs' => [
            'menu' => 'Blogs',
            'menu_desc' => 'Get tips and advice on a great growing your course business',
            'group' => 'resources',
            'icon' => 'fa-files-o',
            'route' => 'website.blogs',
        ],
    ],

    'comparisons' => [
        'studynest-vs-graphy-alternative' => ['title' => 'StudyNest vs Graphy', 'competitor' => 'Graphy'],
        'studynest-vs-teachable-alternative' => ['title' => 'StudyNest vs Teachable', 'competitor' => 'Teachable'],
        'studynest-vs-thinkific-alternative' => ['title' => 'StudyNest vs Thinkific', 'competitor' => 'Thinkific'],
        'studynest-vs-kajabi-alternative' => ['title' => 'StudyNest vs Kajabi', 'competitor' => 'Kajabi'],
        'studynest-vs-podia-alternative' => ['title' => 'StudyNest vs Podia', 'competitor' => 'Podia'],
        'studynest-vs-moodle-alternative' => ['title' => 'StudyNest vs Moodle', 'competitor' => 'Moodle'],
        'studynest-vs-learnworlds-alternative' => ['title' => 'StudyNest vs Learnworlds', 'competitor' => 'Learnworlds'],
        'studynest-vs-edmingle-alternative' => ['title' => 'StudyNest vs Edmingle', 'competitor' => 'Edmingle'],
    ],

    'testimonials' => [
        [
            'quote' => 'They have a fabulous young team that is always full of ideas. Would recommend to everyone without doubt.',
            'name' => 'Rajesh Balasubramanian',
            'role' => 'Founder & Director, 2iim',
            'image' => 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=240&h=240&q=80',
            'rating' => 5,
            'result' => 'Trusted by CAT aspirants nationwide',
        ],
        [
            'quote' => 'StudyNest’s supportive team and user-friendly UI helped us achieve 50x revenue growth—highly recommended!',
            'name' => 'Gomathi Shankar',
            'role' => 'CEO & Founder, Scalpers Trading Academy',
            'image' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=240&h=240&q=80',
            'rating' => 5,
            'result' => '50x revenue growth',
        ],
        [
            'quote' => 'StudyNest values our feedback, listens carefully, and implements changes quickly to improve the platform consistently.',
            'name' => 'Abhiram V',
            'role' => 'Founder & CEO, Tchr',
            'image' => 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=240&h=240&q=80',
            'rating' => 5,
            'result' => 'Rapid product improvements',
        ],
        [
            'quote' => 'Running an online academy with StudyNest has been a complete game-changer, simplifying management and accelerating growth.',
            'name' => 'Vimal Prajapati',
            'role' => 'Founder, Agroacademy',
            'image' => 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=240&h=240&q=80',
            'rating' => 5,
            'result' => 'Simplified academy operations',
        ],
        [
            'quote' => 'StudyNest’s Launcher Plan is perfect for startups, offering quick, helpful support and a seamless experience for MBA prep.',
            'name' => 'Nirmala Shivkumar',
            'role' => 'Director, Elite Prep',
            'image' => 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=240&h=240&q=80',
            'rating' => 5,
            'result' => 'Ideal for early-stage institutes',
        ],
    ],

    'success_stories' => [
        ['title' => 'How EduTap is Revolutionising Ed-Tech in India', 'tag' => 'Banking', 'date' => 'February 27, 2022', 'read' => '5 min read', 'image' => 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&h=500&q=80'],
        ['title' => 'How Xylem Achieved 255 Crores in Just 38 Months', 'tag' => 'NEET', 'date' => 'June 20, 2023', 'read' => '7 min read', 'image' => 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=800&h=500&q=80'],
        ['title' => 'How LCO Grew to a 120 Crore Valuation with StudyNest', 'tag' => 'Coding', 'date' => 'October 22, 2022', 'read' => '5 min read', 'image' => 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=800&h=500&q=80'],
        ['title' => 'How 2IIM Doubled Its Online Business in 18 Months', 'tag' => 'CAT', 'date' => 'November 26, 2022', 'read' => '5 min read', 'image' => 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&h=500&q=80'],
        ['title' => 'How Scalper Academy Achieved 50x Profit Growth', 'tag' => 'Trading', 'date' => 'March 22, 2022', 'read' => '6 min read', 'image' => 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=800&h=500&q=80'],
        ['title' => 'How Sleepy Classes Achieved 2x Student Signups', 'tag' => 'UPSC', 'date' => 'June 26, 2023', 'read' => '5 min read', 'image' => 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=800&h=500&q=80'],
    ],
];
